---
title: "R spatial workshop"
site: distill::distill_website
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

<!-- hide title on this page only -->
```{css}
d-title, d-byline {
  display: none
}
```

<div style="margin-top: 6em; margin-bottom: 3em;">

This is the website for the _R Spatial Workshop_ hosted by the [University of Utah Archaeological Center](https://uuac.utah.edu/) during the summer of 2021. The goal is to introduce participants to methods and techniques for working with spatial data in R. Mostly, that means learning how to work with the [sf](https://r-spatial.github.io/sf/) and [raster](https://rspatial.github.io/raster/reference/raster-package.html) packages. The content and exercises are designed for 3 two-hour meetings.  

### Who is this for? 

Anyone who has (1) a basic understanding of _GIS data and operations_ and (2) a working familiarity with the _R programming language_. If you feel rusty on this, or are very new to these topics, I recommend reading through the bookdown text listed below.  

### Text

All lessons are based on __Lovelace, Nowosad, and Muenchow (2021) Geocomputation with R__. It’s open-source and freely available [here](https://geocompr.robinlovelace.net/). This is an excellent resource, and something I find myself consulting quite often. Exercises are a mix of the exercises provided in that text and my own additions.

### Outline

1. __Day One: Working with `sf`__
    *	Installation and a brief overview of simple features
    * Attribute, spatial, and geometric operations on vectors
    * _Reading: sections on vectors in Ch 2-7_
2. __Day Two: Working with `raster`__
    * Installation and a brief over of rasters
    * Attribute, spatial, and geometric operations on rasters
    * Using simple features in raster operations
    * _Reading: sections on rasters in Ch 2-7_
3. __Day Three: Making thematic maps__
    * Making pretty maps
    * _Reading: Ch 8_

<div>
