
```{r, include = FALSE}
library(dplyr)
library(ggplot2)
library(here)
library(knitr)
library(kableExtra)
library(patchwork)
library(raster)
library(sf)
library(viridis)
```

```{r setup, echo = FALSE}

knitr::opts_chunk$set(echo = TRUE,
                      warning = FALSE,
                      message = FALSE,
                      error = TRUE,
                      collapse = TRUE, # code and output in same block
                      fig.align = "center",
                      fig.retina = 2,
                      fig.asp = 0.7)

options(htmltools.dir.version = FALSE,
        str = strOptions(vec.len = 2))

```

```{r, echo = FALSE}

# define knit_print methods for sf
knit_print.sf <- function(x, ...) print(x, n = 5)

```


```{r xaringan-themer, include = FALSE, warning = FALSE}

library(xaringanthemer)

extra_css <- list(".rred" = list("color" = "var(--text-bold-color)")) 

style_duo_accent(
  primary_color = "#5e5e5e",
  secondary_color = "#CC0000",
  colors = c(white = "#FFFFFF"),
  inverse_header_color = "#FFFFFF",
  code_font_google = google_font("Fira Mono"),
  code_font_size = "0.8rem",
  header_h1_font_size = "45px",
  header_h2_font_size = "35px",
  header_h3_font_size = "20px",
  extra_css = extra_css
)

```

```{r xaringan-animate-css, echo = FALSE}
library(xaringanExtra)
use_animate_css()
```

```{r xaringan-tile-view, echo=FALSE}
xaringanExtra::use_tile_view()
```

```{r xaringan-tachyons, echo=FALSE}
xaringanExtra::use_tachyons()
```

```{css, echo = FALSE}
.pull-lleft {
  float: left;
  width: 25%;
}
.pull-lright {
  float: right;
  width: 74%;
}
.pull-lright ~ * {
  clear: both;
}

.pull-rleft {
  float: left;
  width: 84%;
}
.pull-rright {
  float: right;
  width: 15%;
}
.pull-lright ~ * {
  clear: both;
}

.pull-aleft {
  float: left;
  width: 45%;
}
.pull-aright {
  float: right;
  width: 54%;
}
.pull-aright ~ * {
  clear: both;
}

```

<!-- knit_hook: collapse and print error red
super hacky, see here: https://stackoverflow.com/a/54985678/7705429
we'll need to be careful to not string four # together anywhere


<script>
$(document).ready(function() {
  window.setTimeout(function() {
    $(".hljs-comment:contains('####')").css("color", "red");
    var tmp = $(".hljs-comment:contains('####')").text();
    $(".hljs-comment:contains('####')").text(tmp.replace("####", "##"));
  }, 15);
});
</script>

```{r, include = FALSE, echo = FALSE, eval = FALSE}
local({
  
  hook_error <- knitr::knit_hooks$get("error")
  knitr::knit_hooks$set(error = function(x, options) {
    x <- paste0("##", x)
    x <- sub(" in eval(expr, envir, enclos)", "", x, fixed = TRUE)
    hook_error(x, options)
  })
  
  # hook_message <- knitr::knit_hooks$get("message")
  # knitr::knit_hooks$set(message = function(x, options) {
  #   x <- paste0("##", x)
  #   # x <- sub(" in eval(expr, envir, enclos)", "", x, fixed = TRUE)
  #   hook_message(x, options)
  # })
  
})
```
--->
